### ISSUE TITLE
Pre training on my own dataset

### ISSUE THREAD

**Issue by trinanjan12** [PiotrNawrot/nanoT5#11]
Thank you for the great work. I have some domain specific dataset(large enough), I have trying to do pretraining /continue pretraining for my own dataset. any help on that?
cc @PiotrNawrot

**Comment by PiotrNawrot** [comment]
You need to adapt this [function](https://github.com/PiotrNawrot/nanoT5/blob/main/nanoT5/utils/model_utils.py#L57) to load your dataset. The rest probably should stay the same as it is.

All the best!
