### ISSUE TITLE
query regrading muti-gpu

### ISSUE THREAD

**Issue by trinanjan12** [PiotrNawrot/nanoT5#12]
I have tested the code for ('wikitext','wikitext-2-v1') dataset and my local dataset, the pre training runs on a single machine for the default config. Once I switch to a multigpu set up, I noticed that only one of the gpu is getting loaded, rest are idle. Does the code also support multigpu training out of the box. 
cc  @PiotrNawrot

**Comment by PiotrNawrot** [comment]
Yeah, the code doesn't support multi-gpu at the moment. I'm currently super buys, but it would be a wonderful feature. If you could add a pull-request adding multi-gpu support that would be wonderful!

PS. Next week I'll add another enhancement to the repo with distilled T5 implementation and flash-attention support which speeds up the training 2x!

**Comment by trinanjan12** [comment]
Thank you for getting back @PiotrNawrot . If I am able to make it multi gpu I will create a pr. closing this issue as of now

**Comment by TuTruongVian** [comment]
Any suggestion on multi-GPU implementation? Should DeepSpeed be a good candidate?

**Comment by PiotrNawrot** [comment]
@TuTruongVian anything that works with the current implementation, i.e., training loop being exposed to the user -> not using HF's Trainer. Tbh, I remember that I was testing `accelerate launch` and after setting up the `accelerate` config it worked out of the box without modifying the code! What I didn't check back then is if we need any changes to the code to make sure that it has the same logic.

**Comment by TuTruongVian** [comment]
Thanks for your great work on NanoT5, and quick response. I have a 4-GPU machine and with higher batch_size, it gave out-of- memory error. I realized that NanoT5 uses only 1 GPU. I'll give it a try with "accelerate".

**Comment by PiotrNawrot** [comment]
@TuTruongVian You can always use `optim.grad_acc` to lower the memory requirements : )

**Comment by PiotrNawrot** [comment]
@TuTruongVian btw, next week I'll upload an update which makes training 2x faster and uses less memory : )

**Comment by TuTruongVian** [comment]
Confirm "accelerate launch" works well on my 4 GPU machine. Using python 3.10.10 and pytorch 2.0.0, cuda 11.8

**Comment by vgaraujov** [comment]
@TuTruongVian could you tell me if the resulting pretraining with 4 GPUs works fine? Can you share with me the "accelerate launch" solution? Thanks in advance
