### ISSUE TITLE
pre-train on long context.

### ISSUE THREAD

**Issue by enpassanty** [PiotrNawrot/nanoT5#16]
I need to fine-tune on long context (16K).  Is nanoT5 easily adaptable to longT5 model?  if it is, I could possibly pre-train on c4+my custom data with long context and then fine tune on my custom targets.

**Comment by PiotrNawrot** [comment]
I'm not sure what's the exact architecture of longT5, but as it is in Huggingface you should be able to simply import their modules and swap them with the default T5 modules. Rest of the code stays exactly the same : )
