### ISSUE TITLE
About pre-training on another dataset

### ISSUE THREAD

**Issue by tarudesu** [PiotrNawrot/nanoT5#21]
Hi there, I'm about to pre-train a custom mT5 on my own dataset. But how to do that? (I'm still confused about how to change the script for my dataset or the sample of the dataset I should feed into the model).

Also, I will mix those language texts into one or just pre-train them separately for pre-training.

**Comment by tarudesu** [comment]
For example, I want to fine-tune the translation task with languages A and B. So, should I pre-train T5 on both A-text and B-text? (will it is mixed or have lang_id or something)

**Comment by PiotrNawrot** [comment]
Take a look at these #19 #11 
I believe you should mix different language texts into one.
Lang_id token that would prepend a sequence sounds like something that may prove useful if your data is limited, I've seen this approach in the past, but with the widespread abundance of data you should be fine without it as well!

**Comment by tarudesu** [comment]
Thank you for your response. I'm still confused about the checkpoint path in the default config file. Is it the file for storing checkpoint? (or the path just be used for resuming from the last checkpoint) @PiotrNawrot

**Comment by PiotrNawrot** [comment]
@tarudesu Take a look [here](https://github.com/PiotrNawrot/nanoT5/blob/main/nanoT5/utils/model_utils.py#L27), maybe this helps. It is a path to a PyTorch file storing the model weights.

**Comment by tarudesu** [comment]
I'm still so confused about procedures to pre-train with a custom dataset. Could you tell me how to do it step by step please? Thank you in advance!

(Also give me an example for the full script to pre-train)

**Comment by 4entertainment** [comment]
Hi @tarudesu. First, thank you for commenting this issue.

Could you do the "pre-train a custom mT5 on my own dataset. But how to do that? (I'm still confused about how to change the script for my dataset or the sample of the dataset I should feed into the model)." task?
I want to do same. How can i: 
1) pre-train nano-T5 model on my local dataset? my local dataset will be c4 in first step.
2) change my model to mT5(multilingual)? ( i predict its from utils/modelname...)
3) pre-train my model on my local dataset (not c4. my another dataset from different language..)

**Comment by j1ajunzhu** [comment]
> Hi @tarudesu. First, thank you for commenting this issue.
> 
> Could you do the "pre-train a custom mT5 on my own dataset. But how to do that? (I'm still confused about how to change the script for my dataset or the sample of the dataset I should feed into the model)." task? I want to do same. How can i:
> 
> 1. pre-train nano-T5 model on my local dataset? my local dataset will be c4 in first step.
> 2. change my model to mT5(multilingual)? ( i predict its from utils/modelname...)
> 3. pre-train my model on my local dataset (not c4. my another dataset from different language..)

Hi, so for your solution, firstly, you need to edit ```load_dataset_splits``` function in nanoT5/utils/model_utils.py, you should implement your own data loading approach, and then, you could follow their c4 dataloader for MLM pretrain or you could have a better implementation. For 2 and 3 I have not test yet.
