### ISSUE TITLE
pre-training on local C4 dataset?

### ISSUE THREAD

**Issue by TTTTCoding** [PiotrNawrot/nanoT5#37]
Sorry to bother you, due to network problems, I have downloaded the C4 dataset locally, how can I use the local dataset for pre-training? Please help me with this

**Comment by PiotrNawrot** [comment]
I guess that your best bet would be to refer to the [Huggingface offical guides](https://huggingface.co/docs/datasets/en/loading).
You should be able to solve it by modifying [this function](https://github.com/PiotrNawrot/nanoT5/blob/main/nanoT5/utils/model_utils.py#L73) as guided by Huggingface.
