### ISSUE TITLE
fine-tuning error:  No module named adaptive.moe

### ISSUE THREAD

**Issue by fancyisbest** [PiotrNawrot/nanoT5#5]
Hi Piotr,

your work on the nanoT5 repository is amazing, we like it and want to reproduce.

I study NLP recently, so I have been trying to learn how to run T5 as you do, I successfully pretrained ,but failed fintuning.
and i couldn't execute the fine-tuning python command because the module   adaptive.moe doesn't exist anywhere. 
i also google it ,and can't find the module, so could you help me to figure it out? 

Thanks a lot for your help !
fan

**Comment by PiotrNawrot** [comment]
I'm sorry, it's mistyped in the README.

Please use: `python -m nanoT5.main ...` instead of `python -m adaptive.moe ...`

Thanks for this catch!

**Comment by PiotrNawrot** [comment]
Please let me know if it works now  :)
